db:
  image: mysql:5.7
  # コンテナ名を明示的に指定する
  container_name: db-container
  # ホスト名を明示的に指定する
  hostname: db-server
  ports:
    - '127.0.0.1:3306:3306'
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes_from:
    - data

data:
  image: busybox:1
  # コンテナ名を明示的に指定する
  container_name: data-container
  volumes:
    - ./data:/var/lib/mysql
