version: '3.8'
services:
  db:
    build: ./mysql
    # コンテナ名を明示的に指定する
    container_name: db-container
    # ホスト名を明示的に指定する
    hostname: db-server
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'dbdata:/var/lib/mysql'

volumes:
  dbdata:
