USE mydb;
DROP TABLE IF EXISTS mytable;
CREATE TABLE mytable
(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT
  '主キー',
  jp_name VARCHAR
  (255) COMMENT '和名',
  en_name VARCHAR
  (255) COMMENT '英名',
  hoby VARCHAR
  (255) COMMENT '趣味',
  updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON
  UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
  created_time DATETIME
  NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成時間',
  deleted_time DATETIME COMMENT '削除時間',
  version INT NOT NULL DEFAULT 0 COMMENT 'ロック用更新回数'
)AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;